apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-4iea
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0046-tenant/tkrw-pr712-0075-0046-app/devfile-sample-4iea@sha256:8cc944827b4ca4d6cef6abb143445ec485d3a3842f2220f95da5ae63ad1ec217
        name: my-nodejs
        resources: {}
status: {}
